### ISSUE TITLE
agois/jasperserver-ce:7.5.0 - File does not exist

### ISSUE THREAD

**Issue by Robinyo** [agois-inc/docker-jasperserver-ce#2]
Just tried the new image:

```
FROM agois/jasperserver-ce:7.5.0
```

And then checked the logs:

```
File does not exist: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/accessibility.properties
File does not exist: /etc/java-8-openjdk/accessibility.properties
Buildfile: /usr/src/jasperreports-server/buildomatic/build.xml
[create-ks] A new encryption key and a new keystore are about to be created. Any previously created key and keystore will become invalid and the corresponding passwords unusable. If you think this JasperReports Server instance already has a keystore configured by another OS user, stop this process and configure the path in keystore.init.properties file, then run this command again. See the JasperReports Server Security Guide for details. Do you want to continue? (y/N) 

BUILD FAILED
/usr/src/jasperreports-server/buildomatic/build.xml:58: The following error occurred while executing this line:
/usr/src/jasperreports-server/buildomatic/bin/setup.xml:377: Keystore creation was canceled.

```

**Comment by cleberribeiro** [comment]
I have the same problem

**Comment by Robinyo** [comment]
@cleberribeiro 

I ended up using [js-docker](https://github.com/TIBCOSoftware/js-docker) as a starting point and then I updated it to work with the Community Edition of JasperReports Server.

For example:

```
version: '3.7'

services:

  openldap:
    container_name: openldap
    build:
      context: ./services/openldap
      dockerfile: Dockerfile
    env_file: ./services/openldap/openldap.env
    ports:
      - "389:389"
      - "636:636"

  keycloak:
    container_name: keycloak
    build:
      context: ./services/keycloak
      dockerfile: Dockerfile
    ports:
      - "10001:8080"
      - "10443:8443"
    volumes:
      - .:/export
    env_file: ./services/keycloak/keycloak.env
    depends_on:
      - openldap

  postgres:
    container_name: postgres
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    env_file: ./services/postgres/postgres.env

  pgadmin:
    container_name: pgadmin
    build:
      context: ./services/pgadmin
      dockerfile: Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@serendipity.org.au}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-secret}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - .:/root/.pgadmin

  serendipity-api:
    container_name: serendipity-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/auth/realms/development/protocol/openid-connect/certs
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/serendipity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - keycloak
      - jasperreports-server-cmdline
    command: ["/wait-for-container-to-exit.sh", "jasperreports-server-cmdline", "-t" , "40", "--", "/entrypoint.sh"]

  jasperreports-server:
    container_name: jasperreports-server
    build:
      context: ./services/jasperreports-server
      dockerfile: Dockerfile
    ports:
      - "11001:8080"
      - "11443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./license:/usr/local/share/jasperserver/license
      - ./keystore:/usr/local/share/jasperserver/keystore
    env_file: ./services/jasperreports-server/jasperreports-server.env
    environment:
      - DB_HOST=postgres
    depends_on:
      - jasperreports-server-cmdline
    command: ["/wait-for-container-to-exit.sh", "jasperreports-server-cmdline", "-t" , "30", "--", "/entrypoint-ce.sh", "run"]

  jasperreports-server-cmdline:
    container_name: jasperreports-server-cmdline
    build:
      context: ./services/jasperreports-server
      dockerfile: Dockerfile-cmdline
    volumes:
      - ./license:/usr/local/share/jasperserver/license
      - ./keystore:/usr/local/share/jasperserver/keystore
    env_file: ./services/jasperreports-server/jasperreports-server.env
    environment:
      - DB_HOST=postgres
      - JRS_LOAD_SAMPLES=true
    depends_on:
      - postgres
    command: ["/wait-for-it.sh", "postgres:5432", "-t" , "30", "--", "/entrypoint-cmdline-ce.sh", "init"]
```

Ref:
- [Building the JasperReports Server image](https://github.com/Robinyo/serendipity-api/tree/master/projects/spring-boot/server/services/jasperreports-server)
